### ISSUE TITLE
Implementation of yml

### ISSUE THREAD

**Issue by raghavzversal** [raghavzversal/Teacher#1]
1. Introduction to Docker and yml.
2. Implementation of yml.

**Comment by raghavzversal** [comment]
Encountered the following error while building docker image
failed to solve with frontend dockerfile.v0: failed to create LLB definition: failed to do request: Head "https://registry-1.docker.io/v2/library/openjdk/manifests/8": net/http: TLS handshake timeout

working to resolve the following error

**Comment by raghavzversal** [comment]
solution  
docker desktop > settings > docker engine > change buildkit to false
as shown below
{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "experimental": false,
  "features": {
    "buildkit": false
  }
}

**Comment by raghavzversal** [comment]
Approach:
1. src>docker>Dockerfile 
**Inside Dockerfile**
FROM openjdk:12-jdk-alpine
VOLUME /tmp
ARG JAR_FILE
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]

2. Inside build.gradle

**Add following plug in:**
plugins {
    id 'com.palantir.docker' version '0.22.1'
}

**Inside docker {}**
docker
{
	name "teacherportal"
	dockerfile file('src/docker/Dockerfile')
	copySpec.from(jar).rename(".*", "app.jar")
	buildArgs(['JAR_FILE': "app.jar"])
}

3. Terminal 
> gradle tasks
> gradle clean build
> gradle docker --info
>docker images //gets you all the images in the system.
>docker run teacherportal //as per my code.

Testing result: failed
error: no main manifest attribute, in /app.jar

Working on resolvement

**Comment by raghavzversal** [comment]
https://github.com/palantir/gradle-docker

**Comment by raghavzversal** [comment]
Script added to build.gradle 
jar {
    manifest {
        attributes 'Main-Class': 'com.zversal.teacherportal.main.Main'
    }
}

new error detected
Exception in thread "main" java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariDataSource
        at com.zversal.teacherportal.database.ManagerDB.<init>(ManagerDB.java:16)
        at com.zversal.teacherportal.main.Main.<clinit>(Main.java:19)
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariDataSource
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 2 more

error caused due to hikari used for database

**Comment by raghavzversal** [comment]
Error resolved
Cause of problem: inavailablity of jars over runtime environment
Solution
below script added 
from { configurations.runtimeClasspath.collect{it.isDirectory() ? it:zipTree(it) }}

for e.g
jar 
{
	manifest 
	{
		attributes 'Main-Class': 'com.zversal.teacherportal.main.Main'
	}
	from { configurations.runtimeClasspath.collect{it.isDirectory() ? it:zipTree(it) }}
}

working on new approach

**Comment by raghavzversal** [comment]
Error

Entry META-INF/NOTICE.txt is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.2/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.

Solution
duplicatesStrategy(DuplicatesStrategy.EXCLUDE)

e.g

jar{
	duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
	manifest {
		attributes "Main-class": "$mainClassName"
		}
		from { configurations.runtimeClasspath.collect{it.isDirectory() ? it:zipTree(it) }}
	}

**Comment by raghavzversal** [comment]
Docker image for a Gradle project successfully created, the project is using spark environment and currently able to work on getting requests.
The project is pushed at issue-v1.1.
The project at issue-1-fix has internal errors hence causing problems while creating docker image for the same.
